name: Docker Build and Publish

on:
  push:
    branches:
      - dev
      - stage
      - master

  workflow_dispatch:
    inputs:
      semverIncrementLevel:
        description: 'Level of the semver (major.minor.patch) to be increased to get the new package version.'
        required: true
        default: 'patch'

env:
  IMAGE_NAME: "barong"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2

      - name: Bump version
        id: bumpVersion
        uses: trakx/bump-version-action/get-tag@v9.1.3
        with:
          semverIncrementLevel: ${{github.event.inputs.semverIncrementLevel}}

      - name: Build image and tag image
        run: |
          docker build . \
            --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:${{steps.bumpVersion.outputs.fullVersion}}"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Publish to GPR
        run: |
          docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:${{steps.bumpVersion.outputs.fullVersion}}"
